In [2]:
import numpy as np
import collections as cl

P2 = np.array([
    [0.25, 0.10, 0.25],
    [0.50, 0.80, 0.50],
    [0.25, 0.10, 0.25]],dtype=np.float32)
P1 = np.array([
    [0.30, 0.20, 0.50],
    [0.50, 0.30, 0.20],
    [0.20, 0.50, 0.30]],dtype=np.float32)
S = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]])

ts = [1,2,4,8,16,32]

## Task 14.1: evolution of a Markov process

In [3]:
for t in ts:
    pi = np.linalg.matrix_power(P2,t) @ S
    print("pi[{}] = \n{}".format(str(t), pi))
    print()

pi[1] = 
[[0.25       0.1        0.25      ]
 [0.5        0.80000001 0.5       ]
 [0.25       0.1        0.25      ]]

pi[2] = 
[[0.175      0.13000001 0.175     ]
 [0.64999998 0.74000001 0.64999998]
 [0.175      0.13000001 0.175     ]]

pi[4] = 
[[0.14575    0.14170001 0.14575   ]
 [0.70849997 0.7166     0.70849997]
 [0.14575    0.14170001 0.14575   ]]

pi[8] = 
[[0.14288059 0.14284778 0.14288059]
 [0.71423882 0.71430445 0.71423882]
 [0.14288059 0.14284778 0.14288059]]

pi[16] = 
[[0.14285715 0.14285715 0.14285715]
 [0.71428567 0.71428567 0.71428567]
 [0.14285715 0.14285715 0.14285715]]

pi[32] = 
[[0.14285715 0.14285715 0.14285715]
 [0.71428567 0.71428567 0.71428567]
 [0.14285715 0.14285715 0.14285715]]



In [4]:
for t in ts:
    pi = np.linalg.matrix_power(P1,t) @ S
    print("pi[{}] = \n{}".format(str(t), pi))
    print()

pi[1] = 
[[0.30000001 0.2        0.5       ]
 [0.5        0.30000001 0.2       ]
 [0.2        0.5        0.30000001]]

pi[2] = 
[[0.28999999 0.37       0.34000003]
 [0.34       0.29000002 0.37      ]
 [0.37       0.34000003 0.29000002]]

pi[4] = 
[[0.33570001 0.33020005 0.33410004]
 [0.33410001 0.33570004 0.33020002]
 [0.33020002 0.33410004 0.33570004]]

pi[8] = 
[[0.33333418 0.33331916 0.33334684]
 [0.33334681 0.33333421 0.33331913]
 [0.33331913 0.33334684 0.33333418]]

pi[16] = 
[[0.33333343 0.33333346 0.33333343]
 [0.33333343 0.33333346 0.33333343]
 [0.33333343 0.33333346 0.33333343]]

pi[32] = 
[[0.33333355 0.33333358 0.33333355]
 [0.33333355 0.33333358 0.33333355]
 [0.33333355 0.33333358 0.33333355]]



In [5]:
np.linalg.eig(P2)

(array([ 1.000000e+00, -5.769797e-17,  3.000000e-01], dtype=float32),
 array([[ 1.9245009e-01,  7.0710677e-01,  4.0824831e-01],
        [ 9.6225047e-01,  2.5633392e-17, -8.1649655e-01],
        [ 1.9245009e-01, -7.0710677e-01,  4.0824831e-01]], dtype=float32))

In [6]:
np.linalg.eig(P1)

(array([ 1.        +0.j        , -0.04999999+0.25980762j,
        -0.04999999-0.25980762j], dtype=complex64),
 array([[ 0.57735026+0.j ,  0.57735026+0.j ,  0.57735026-0.j ],
        [ 0.57735026+0.j , -0.28867513-0.5j, -0.28867513+0.5j],
        [ 0.57735026+0.j , -0.28867513+0.5j, -0.28867513-0.5j]],
       dtype=complex64))

## Task 14.2: sampling a Markov process

In [7]:
import numpy.random as rnd

states = ['A', 'B', 'C']
indices = range(len(states))
state2index = dict(zip(states, indices))
index2state = dict(zip(indices, states))

def generateStateSequence(X0, P, tau):
    sseq = [X0]
    iold = state2index[X0]
    for t in range(tau-1):
        inew = rnd.choice(indices, p=P[:,iold])
        sseq.append(index2state[inew])
        iold = inew
    return sseq

def generate_episoids(X0, P, tau=10, times=10000):
    episoids = np.zeros((times, tau)).astype(object)
    for i in range(times):
        sequence = generateStateSequence(X0, P, tau)
        episoids[i] = np.array(sequence)
    return episoids

In [8]:
episoids1 = generate_episoids('A', P1)
episoids2 = generate_episoids('C', P2)


In [9]:
occurences = cl.Counter(episoids1[:,-1])
for state, occ in occurences.items():
    print(state, occ/10000)


C 0.3389
B 0.3278
A 0.3333


In [10]:
occurences = cl.Counter(episoids2[:,-1])
for state, occ in occurences.items():
    print(state, occ/10000)

B 0.7158
C 0.1339
A 0.1503
